name: "Neon Database Create Branch Action"
author: "Neon Database"
description: "Creates a new Neon Postgres branch based a parent branch."
branding:
  icon: "box"
  color: "green"

inputs:
  project_id:
    required: true
    type: string
  parent_branch_id:
    required: true
    type: string
  branch_name:
    required: false
    type: string
  api_key:
    required: true
    
outputs:
  branch_id:
    description: "Newly created branch Id"
    value: ${{ steps.output-branch-id.outputs.branch_id }}

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        OUTPUT=`curl -X 'POST' \
        'https://console.neon.tech/api/v2/projects/${{inputs.project_id}}/branches' \
        -H 'accept: application/json' \
        -H 'Authorization: Bearer ${{ inputs.api_key }}' \
        -H 'Content-Type: application/json' \
        -d '{
        "branch": {
          "parent_id": "${{inputs.parent_branch_id}}",
          "name": "${{inputs.branch_name}}"
        }
        }'`
        echo $OUTPUT > output.json
#     - uses: notiz-dev/github-action-json-property@release
#       id: format_script
#       with: 
#         path: 'output.json'
#         prop_path: 'branch.id'
#     - run: echo ${{steps.format_script.outputs.prop}} >> $GITHUB_OUTPUT
#       shell: bash
#       id: output-branch-id
