name: "Neon Database Create Branch Action"
author: "Neon Database"
description: "Creates a new Neon Postgres branch based a parent branch."
branding:
  icon: "box"
  color: "green"

inputs:
  project_id:
    required: true
    type: string
  branch_name:
    required: false
    type: string
  api_key:
    required: true
  username:
    required: true
  password:
    required: true
    
outputs:
  db_url:
    description: "New branch DATABASE_URL"
    value: ${{ steps.create-branch.outputs.db_url }}

runs:
  using: "composite"
  steps:
    - name: Create new Neon branch
      env:
        PROJECT_ID: ${{ inputs.project_id }}
        API_KEY: ${{ inputs.api_key }}
        BRANCH_NAME: ${{ inputs.branch_name }}
        PGUSERNAME: ${{ inputs.username }}
        PGPASSWORD: ${{ inputs.password }}
      shell: bash
      id: create-branch
      run: |
        branch=$(curl --silent \
          "https://console.neon.tech/api/v2/projects/${PROJECT_ID}/branches" \
          --header "Accept: application/json" \
          --header "Content-Type: application/json" \
          --header "Authorization: Bearer ${API_KEY}" \
          --data "{
            \"branch\": {
              \"name\": \"${BRANCH_NAME}\"
            },
            \"endpoints\": [
              {
                \"type\": \"read_write\"
              }
            ]
          }")
          
        host=$(echo $branch | jq --raw-output '.endpoints[0].host')
        echo "host=${host}" >> $GITHUB_OUTPUT
        echo "db_url=postgres://${PGUSERNAME}:${PGPASSWORD}@${host}" >> $GITHUB_OUTPUT
